### PR TITLE
fix: ced-835 Making coverImageUrl optional

### PR DESCRIPTION
**Pull request by lazard9**
### 🔗 Linked issue
https://energysage.atlassian.net/browse/CED-835

### ❓ Type of change
- Fixing ArticleVideo cover image CLS and lazy loading

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
- To prevent errors from appearing in the console, coverImageUrl is now optional since we are using slot place for the StoryblokImage component.

### 🥼 Testing
- Manual testing

#### 🧐 Feedback Requested / Focus Areas

-

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Review by ericdouglaspratt — CHANGES_REQUESTED** [review]
`coverImageUrl` looks good but I it looks like `altText` is still required - did you mean to change that one too?

**Comment by lazard9** [comment]
> `coverImageUrl` looks good but I it looks like `altText` is still required - did you mean to change that one too?

The video component requires `altText` for the title `:title="altText"`. Therefore we can keep it as required.

**Review by suleiy — APPROVED** [review]
Looks good to me!

**Review by ericdouglaspratt — CHANGES_REQUESTED** [review]
Since `altText` is required and used in both cases (slot and coverImageUrl), can we update the `<b-img v-else-if="altText && coverImageUrl"` to remove `altText` from that conditional? That would help make it clearer to those reading the code that `altText` is not only used in the `<b-img>` case, and all the `<b-img>` needs beyond the what the slot needs is the `coverImageUrl`.

**Review by ericdouglaspratt — APPROVED** [review]

**Pull request merged**
