### PR TITLE
feat: new labelSrOnly prop for EsFormInput

### PR DESCRIPTION
**Pull request by ericdouglaspratt**
### 🔗 Linked issue

- https://energysage.atlassian.net/browse/ESDS-127

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Added a `labelSrOnly` prop to EsFormInput for cases where the form consists of only an input and a submit button within a stylized marketing section like a hero or a CTA banner, and the placeholder text is used as the label for visual users.
- Simplified and broadened the number of examples on the EsFormInput page.

#### Top of EsFormInput page with new basic and required examples
Screen Shot 2023-02-23 at 5 06 30 PM

#### New error and success state examples
Screen Shot 2023-02-23 at 5 06 40 PM

#### New placeholder and hidden label examples
Screen Shot 2023-02-23 at 5 06 49 PM

#### Simplified context message examples
Screen Shot 2023-02-23 at 5 06 55 PM

### 🥼 Testing

- Tested on docs page in Chrome with responsive devtools

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Review by RyanMulready — COMMENTED** [review]
I like the concept here and can think of a few different use cases. I played around with trying to accomplish one of them locally but it ended up illustrating a difference in height between our inputs and buttons that becomes more obvious with a pattern like this.

image


Here it is with a slight adjustment in button height

```
  height: $font-size-base * 3.15; // ensures consistent button height, matching the design, regardless of content
```

image


Thoughts?

**Comment by ericdouglaspratt** [comment]
@RyanMulready Yes, the height difference is a problem I intended to solve separately from this, and I wanted to use the docs example to call out (a) a real-world use case for needing `labelSrOnly`, but (b) this exact issue.

For the moment, on homepage, I'm solving it by using CSS to set the same height as the button, but we'll want to do a PR fairly soon (which I could tackle) to fix. In #501, I deliberately only applied the fixed heights to the button styles, despite us having a pattern of `$input-btn-xxx` variables that make them match, because (a) there was both a default and small height in play and small definitely didn't make sense for inputs, and (b) I wasn't sure yet if inputs needed to be the same height as buttons. Now I am, for this use case.

When we do that, I'd rather not change the button heights, as those are pretty solid and in line with the designs. I'd rather update the input heights to match the default button height, using that `$input-btn-xxx` height variable pattern. But would have to verify that the text size in inputs plus the padding of inputs wouldn't naturally go beyond that height, so I figured a separate PR and ticket for that investigation and fix.

As for whether the button should be separate or appear "joined" to the input (the latter I did initially implement for the stubbed-out homepage components), I've now seen both treatments in the homepage designs (the newer ones have them separated out), so I'd want to check in with design on that before putting effort into joining them.

**Comment by RyanMulready** [comment]
> @RyanMulready Yes, the height difference is a problem I intended to solve separately from this, and I wanted to use the docs example to call out (a) a real-world use case for needing `labelSrOnly`, but (b) this exact issue.
> 
> For the moment, on homepage, I'm solving it by using CSS to set the input to the same height as the button, but we'll want to do a PR fairly soon (which I could tackle) to fix. In #501, I deliberately only applied the fixed heights to the button styles, despite us having a pattern of `$input-btn-xxx` variables that make them match, because (a) there was both a default and small height in play and small definitely didn't make sense for inputs, and (b) I wasn't sure yet if inputs needed to be the same height as buttons. Now I am, for this use case.
> 
> When we do that, I'd rather not change the button heights, as those are pretty solid and in line with the designs. I'd rather update the input heights to match the default button height, using that `$input-btn-xxx` variable pattern. But would have to verify that the text size in inputs plus the padding of inputs wouldn't naturally go beyond that height, so I figured a separate PR and ticket for that investigation and fix. Created [energysage.atlassian.net/browse/ESDS-128](https://energysage.atlassian.net/browse/ESDS-128) to capture this work.

Seems like a reasonable approach to me. Thank you for creating a ticket. 

> As for whether the button should be separate or appear "joined" to the input (the latter I did initially implement for the stubbed-out homepage components), I've now seen both treatments in the homepage designs (the newer ones have them separated out), so I'd want to check in with design on that before putting effort into joining them.

I suppose offering both in documentation isn't the best idea even if both patterns exist in the wild. I think asking for clarification from design on which should be the documented pattern is right.

**Comment by ericdouglaspratt** [comment]
@RyanMulready Just asked in the ESDS core team channel and both Huanran and Maria confirmed the separated input and button are the finalized version, and the joined version was just an exploration, so this should be good to go.

**Review by RyanMulready — APPROVED** [review]

**Pull request merged**
