### PR TITLE
feat: added animation to modal

### PR DESCRIPTION
**Pull request by ericdouglaspratt**
### 🔗 Linked issue

- https://energysage.atlassian.net/browse/CED-1832

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Added open and close animation to modal that mirrors the nice one from PrimeVue
- Added animation for the modal mask (backdrop)
- Made animation only happen if the user hasn't set a "reduce motion" preference

### 🥼 Testing

- Tested locally, with macOS accessibility setting "Reduce motion" on and off (had to restart Chrome)

#### 🧐 Feedback Requested / Focus Areas

- Overall

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Comment by nathanielwarner** [comment]
👀

**Review by tomleo — APPROVED** [review]
Aside from the transition on mask which I'm not sure about without digging into, this looks good 👍

**Review by nathanielwarner — CHANGES_REQUESTED** [review]
This is a step in the right direction! For the background color transition, you just need to use the `:has` selector to check the state of the transition from within the mask CSS.

This is the contents of _modal.scss after my fix:
```
.es-modal-mask {
  &:has(.es-modal-enter-active, .es-modal-leave-active) {
    transition: background-color 150ms cubic-bezier(0.4, 0, 0.2, 1);
  }

  &:has(.es-modal-enter-from, .es-modal-leave-to) {
    background-color: transparent;
  }

  &:has(.es-modal-enter-to, .es-modal-leave-from), &:not(:has(.es-modal-enter-active, .es-modal-leave-active)) {
    background-color: rgba(0, 0, 0, 0.075);
  }
}

.es-modal-enter-active,
.es-modal-leave-active {
  transition: all 150ms cubic-bezier(0.4, 0, 0.2, 1);
}
.es-modal-enter-from,
.es-modal-leave-to {
  opacity: 0;
  transform: scale(0.8);
}
.es-modal-enter-to,
.es-modal-leave-from {
  opacity: 1;
  transform: scale(1);
}
```

**Comment by ericdouglaspratt** [comment]
@nathanielwarner Thanks! Didn't know about the `has()` selector but that is perfect, TIL CSS can do that now. I still think this is a hole in PrimeVue docs and maybe even unstyled functionality but at least we can do what we want!

**Review by nathanielwarner — APPROVED** [review]
LGTM! 🚀 

> Thanks! Didn't know about the has() selector but that is perfect, TIL CSS can do that now.

Yeah I learned about it recently as well and have found it quite useful on a few occasions! Shoutout to the people who create CSS for making improvements

**Pull request merged**
