### PR TITLE
feat: extract data-table styles to es-bs-base

### PR DESCRIPTION
**Pull request by tomleo**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Extract `EsDataTable` styles into `es-bs-base` so that they can be used in other components

### 🥼 Testing

Manual, comparing current (on the left) to development (on the right)

Screen Shot 2024-02-15 at 4 30 59 PM

#### 🧐 Feedback Requested / Focus Areas

- Ideally there aren't any visual regressions 

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Review by nathanielwarner — CHANGES_REQUESTED** [review]
I'm not sure specifically why, but the colors isn't working the same way as before.

On https://design.energysage.dev/molecules/es-data-table/
Screenshot 2024-02-16 at 11 45 00 AM

On http://localhost:8500/molecules/es-data-table
Screenshot 2024-02-16 at 11 44 54 AM

**Comment by tomleo** [comment]
@nathanielwarner Great eye! Although I'm not able to reproduce. I added [percy visual regression testing](https://percy.io/d5133463/es-ds/builds/32704620/unchanged/1795049322?browser=safari&browser_ids=47%2C56%2C57%2C58&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=original&width=1280&widths=375%2C1280) which don't detect a change.

Could you try running `make build`? I wonder if `es-vue-base` might have been reloaded without also re-compiling `es-bs-base`.

**Review by nathanielwarner — CHANGES_REQUESTED** [review]
There's still something wrong with the colors on one of the demos:

Screenshot 2024-02-19 at 10 53 19 AM

I looked at the code and I'm having trouble figuring out *why* it is. But it's odd that the visual regression testing didn't catch it.

**Comment by ericdouglaspratt** [comment]
Weird, I'm also not able to reproduce. I tried switching to this branch and just doing `make dev`, as well as a full rebuild via the [six commands](https://github.com/EnergySage/es-ds?tab=readme-ov-file#installing-dependencies-and-linking-packages) and then `make dev`, and tabbing back and forth between https://design.energysage.dev/molecules/es-data-table and localhost and don't see any differences in the column header styling or the zebra-striping on the first column.

**Review by nathanielwarner — APPROVED** [review]
Confirmed that things are working with Eric's commit!

**Pull request merged**
