### PR TITLE
feat: responsive font size utility classes

### PR DESCRIPTION
**Pull request by ericdouglaspratt**
### 🔗 Linked issue

- https://energysage.atlassian.net/browse/ESDS-142

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Added new static font size utility classes based on a numbered naming scheme (e.g. 50, 75, 100, 200, etc.)
- Added new responsive font size utility classes based on the same numbered naming scheme (e.g. `font-size-lg-400`)
- Upgraded the tables on the Typography docs page to be responsive (for both font size and font weight)
- Deprecated the old font size utility classes (e.g. `font-size-sm`)
- Updated all usages within ESDS of the deprecated classes with the new ones

#### New font size table on desktop
Screen Shot 2023-03-22 at 4 27 35 PM

#### New font size table on mobile
Screen Shot 2023-03-22 at 4 26 37 PM

#### Deprecated font size table on desktop
Screen Shot 2023-03-22 at 4 28 20 PM

#### Deprecated font size table on mobile
Screen Shot 2023-03-22 at 4 28 48 PM

#### Updated font weight table on desktop
Screen Shot 2023-03-22 at 4 29 16 PM

#### Updated font weight table on mobile
Screen Shot 2023-03-22 at 4 29 27 PM

### 🥼 Testing

- Tested Typography docs page in Chrome responsive devtools, Firefox, and Safari
- Tested a `<p>` tag using a different responsive font size utility class at every breakpoint to verify correct generation of utility classes

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Comment by tomleo** [comment]
It seems to go up by increments of 25, then it jumps to increments of 100. That being said, `font-size-100` certainly shouldn't be less than the base-font-size.

I tried playing around with a few different schemes here: https://docs.google.com/spreadsheets/d/1nJk6Zr_lQmNHgJ1mMQl2V956U-pfJ03IflaKAVS_nJ0/edit?usp=sharing

Don't really like any of the naming schemes 🤣

**Review by tomleo — APPROVED** [review]
Willing to give this new naming scheme a shot 👍

**Comment by ericdouglaspratt** [comment]
Yeah unlike the new spacing naming scheme, our font sizes aren't mathematically related enough to generate something clean. Sometimes it's a multiplier of 1.125 up from the previous size, more often it's 1.25, but occasionally 1.2, and once nothing standard at all. ([my initial analysis here](https://energysage.atlassian.net/wiki/spaces/DS/pages/217120806/Proposed+Typography+Normalization))

I made 12px and 14px 50 and 75 respectively because yes - 100 should be base, those need to be smaller, and hopefully we shouldn't any other sizes smaller than 16px.

And I liked the cleanliness of Adobe Spectrum's increment-by-100 naming scheme so I figured I'd adopt it here.
https://spectrum.adobe.com/page/typography/#Font-sizes

There is a risk that we adjust font sizes (especially the larger ones) in the future, but we can make a judgement call at that time whether a minor breaking change is worth it (or perhaps intentional, if we want all uses of that font size to change to the new font size) or if we want to insert a 50 in the middle somewhere.

**Review by RyanMulready — APPROVED** [review]
Looks good to me, one thing to call out, and this isn't new to this PR, we've adopted a pattern where `es-vue-base` is reliant upon a matching version number of `es-bs-base`. We may want to add that to docs. [README.md](https://github.com/EnergySage/es-ds/blob/main/es-vue-base/README.md)

**Pull request merged**
