### PR TITLE
CSM-2859: Fixing Multiple File Download Bug

### PR DESCRIPTION
**Pull request by satwikgoyal**
### 🔗 Linked issue

- https://energysage.atlassian.net/browse/CSM-2859

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Earlier when uploading a file one _after_ another in the same session would throw an error saying "You have already uploaded a file with the name "{fileName}". Please rename your file and try again.". This was caused because when the second file was being uploaded, we were re-uploading the first file causing issues when downloading these files.
- In `es-vue-base/src/lib-components/EsFileInput.vue` now uploading only `newValidFiles` instead of all `files`

### 🥼 Testing

- There are 3 ways we can test these changes:
   - Deploy this to production and then test out changes in `es-cdgm`
   - You'll need to symlink `~/Dev/es-ds/es-vue-base/dist` to `~/Dev/-es-cdgm/frontend/node_modules/@energysage/es-vue-base` (https://docs.npmjs.com/cli/v9/commands/npm-link)
   - Quick and dirty testing: copy the file in `es-cdgm` and import it from local components instead of `es-ds`
- Then upload files one _after_ another and try downloading them as a developer
- Try other ways to possibly cause these issues such as drag and drop or uploading multiple files at _once_, etc

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Review by zacharyjarnagin — COMMENTED** [review]
I am not sure if we care about this use case but:

1. Upload a file
2. Upload a different file
3. Click submit

Only the last file gets uploaded. If that is okay, then this PR is good to go! Otherwise, we may need an additional map

**Review by zacharyjarnagin — APPROVED** [review]
After discussion, seems like my comment is the intended flow! Nice work

**Comment by satwikgoyal** [comment]
> I am not sure if we care about this use case but:
> 
> 1. Upload a file
> 2. Upload a different file
> 3. Click submit
> 
> Only the last file gets uploaded. If that is okay, then this PR is good to go! Otherwise, we may need an additional map

For future developers: this case will be handled by the code.

**Comment by satwikgoyal** [comment]
@zacharyjarnagin I found an edge case that I resolved today. As a combination to this branch I created another one in `es-cdgm` here: https://github.com/EnergySage/es-cdgm/pull/3044. Please lmk what you think about this.

**Review by zacharyjarnagin — APPROVED** [review]
Tested and verified working!! Nice job

**Pull request merged**
