### PR TITLE
CED-1446: EsReviewsIoCardCarousel restyling

### PR DESCRIPTION
**Pull request by hroth1994**
### 🔗 Linked issue

* https://energysage.atlassian.net/browse/CED-1446

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

* Updated caret style, shadows, star color, hover state, padding, font size, font weight, and line height based on design
* Added period to end of author name to match design
* Updated popup to match EsModal (as closely as possible)
* Involved a refactor to move styles from es-vue-base into es-bs-base

### 🥼 Testing

* Tested the changes locally on http://localhost:8500/organisms/es-reviews-io-card-carousel
* Tested that all style changes were also applied to mobile

#### 🧐 Feedback Requested / Focus Areas

- General feedback

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [ ] I have documented testing approach

### CODE REVIEW

**Comment by nathanielwarner** [comment]
👀

**Review by ericdouglaspratt — CHANGES_REQUESTED** [review]
Looks great!

Can we also adopt the focus and active states of interactive cards? When I tab to a card, it gets an ugly black outline around it that's only partially visible.
Screen Shot 2024-05-10 at 9 56 53 AM

**Review by ericdouglaspratt — CHANGES_REQUESTED** [review]
Also if you update from the feature branch, I finalized the Modal styling yesterday with updates to the color and size of the X icon in the close button and a new example with the bordered footer - could use that border color for the one in the Reviews.io modal.

Screen Shot 2024-05-10 at 10 02 02 AM

**Review by ericdouglaspratt — APPROVED** [review]
Looks good!

**Pull request merged**
