### PR TITLE
feat: add reviews.io component

### PR DESCRIPTION
**Pull request by nathanielwarner**
### 🔗 Linked issue

https://energysage.atlassian.net/browse/CED-408

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds the reviews.io component that is currently defined in `es-cms-pages`. It will be removed from there after this change is published.

In the course of migrating the component, I noticed a bug, where navigating away from the page leaves behind the text that was in the reviews.io review. It appears that this text makes up the modals that are normally hidden, so it's not visible on the page itself. When navigating away, the styles disappear so it is visible. To fix this, I added the hook `beforeRouteLeave` to remove this left-behind text upon leaving the page.

### 🥼 Testing

Manual testing

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [x] I have documented testing approach

### CODE REVIEW

**Review by ericdouglaspratt — CHANGES_REQUESTED** [review]
Looks great overall, thanks for putting this in!

One thing - I think we should align with the naming convention of the other molecules/organisms in the design system by prefixing with "Es".

**Comment by nathanielwarner** [comment]
> Looks great overall, thanks for putting this in!
> 
> One thing - I think we should align with the naming convention of the other molecules/organisms in the design system by prefixing with "Es".

All set!

**Review by ericdouglaspratt — APPROVED** [review]

**Review by lgeggleston — CHANGES_REQUESTED** [review]
Hi! Code looks good, thanks for catching that bug & adding the `beforeRouteLeave` as well!

The component itself needs to be in `es-vue-base/src/lib-components` though I think; `es-design-system` is just the [documentation pages](https://github.com/EnergySage/es-ds#the-parts) that display an example of that component in use.
[This informal doc](https://energysage.atlassian.net/wiki/spaces/CPod/pages/249102350/Using+the+design+system+notes) is helpful too for testing with that pattern & rebuilding `es-vue-base` to see changes.

**Comment by ericdouglaspratt** [comment]
Lia's absolutely right, it needs to be in `es-vue-base` and then imported into `es-design-system` to display on the docs page - apologies for the miss - it's been a hectic day!

**Comment by nathanielwarner** [comment]
> es-design-system is just the [documentation pages](https://github.com/EnergySage/es-ds#the-parts) that display an example of that component in use

That... actually makes a lot of sense. My apologies, as I've never worked in this repo before!

**Review by lgeggleston — APPROVED** [review]
Looks good! Tested on multiple browsers & viewports :ship:

**Pull request merged**
